In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import os

In [2]:
filename = "Data\\2018_full.csv"

In [3]:
def p2f(s):
    try:
        return float(s)
    except ValueError:
        return 0

In [4]:
def alphabetize(dataframe):
    cols = dataframe.columns.tolist()
    cols = sorted(cols)
    cols.remove("Label")
    cols.insert(0, "Label")
    return dataframe[cols]

In [5]:
data = pd.read_csv(filename)
data

,Label,Alaska!!Total!!Estimate,Alaska!!Total!!Margin of Error,Alaska!!Percent!!Estimate,Alaska!!Percent!!Margin of Error,Maine!!Total!!Estimate,Maine!!Total!!Margin of Error,Maine!!Percent!!Estimate,Maine!!Percent!!Margin of Error,North Carolina!!Total!!Estimate,...,District of Columbia!!Percent!!Estimate,District of Columbia!!Percent!!Margin of Error,Utah!!Total!!Estimate,Utah!!Total!!Margin of Error,Utah!!Percent!!Estimate,Utah!!Percent!!Margin of Error,New York!!Total!!Estimate,New York!!Total!!Margin of Error,New York!!Percent!!Estimate,New York!!Percent!!Margin of Error
0,Citizens 18 years and over,"532,244","±2,539",(X),(X),"1,070,661","±2,844",(X),(X),"7,629,700",...,(X),(X),"2,087,341","±6,918",(X),(X),"13,770,029","±25,984",(X),(X)
1,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18 to 29 years,"127,476","±1,829",24.0%,±0.3,"181,628","±1,434",17.0%,±0.1,"1,605,709",...,27.6%,±0.3,"567,726","±3,742",27.2%,±0.2,"2,924,030","±11,192",21.2%,±0.1
3,30 to 44 years,"144,647","±2,629",27.2%,±0.5,"227,304","±2,280",21.2%,±0.2,"1,755,720",...,31.5%,±0.5,"596,259","±5,266",28.6%,±0.2,"3,189,035","±14,820",23.2%,±0.1
4,45 to 64 years,"174,789","±3,032",32.8%,±0.5,"388,346","±2,124",36.3%,±0.2,"2,604,091",...,25.0%,±0.3,"578,946","±3,748",27.7%,±0.2,"4,615,032","±13,503",33.5%,±0.1
5,65 years and over,"85,332","±1,468",16.0%,±0.3,"273,383","±1,126",25.5%,±0.1,"1,664,180",...,15.8%,±0.2,"344,410","±2,279",16.5%,±0.1,"3,041,932","±7,702",22.1%,±0.1
6,SEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Male,"279,792","±1,890",52.6%,±0.3,"518,367","±1,899",48.4%,±0.2,"3,634,888",...,46.7%,±0.3,"1,041,497","±4,863",49.9%,±0.1,"6,565,089","±16,713",47.7%,±0.1
8,Female,"252,452","±2,008",47.4%,±0.3,"552,294","±2,632",51.6%,±0.2,"3,994,812",...,53.3%,±0.3,"1,045,844","±4,348",50.1%,±0.1,"7,204,940","±15,539",52.3%,±0.1
9,RACE AND HISPANIC ORIGIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,White alone,"368,438","±2,822",69.2%,±0.5,"1,027,268","±1,780",95.9%,±0.2,"5,476,286",...,45.6%,±0.5,"1,878,243","±6,805",90.0%,±0.3,"9,479,819","±24,931",68.8%,±0.2
11,Black or African American alone,"17,519","±1,558",3.3%,±0.3,"8,276","±1,369",0.8%,±0.1,"1,673,716",...,45.8%,±0.6,"22,236","±1,528",1.1%,±0.1,"2,139,909","±15,967",15.5%,±0.1
12,Asian alone,"26,468","±2,068",5.0%,±0.4,"8,429",±998,0.8%,±0.1,"142,490",...,3.6%,±0.4,"41,022","±3,133",2.0%,±0.1,"922,184","±12,412",6.7%,±0.1
13,American Indian and Alaska Native alone,N,N,N,N,N,N,N,N,"89,491",...,N,N,N,N,N,N,"56,168","±4,696",0.4%,±0.1
14,Native Hawaiian and Other Pacific Isla...,"4,320","±1,128",0.8%,±0.2,N,N,N,N,"5,707",...,N,N,"17,875","±1,551",0.9%,±0.1,"7,021","±2,370",0.1%,±0.1
15,Some Other Race alone,"6,980","±1,974",1.3%,±0.4,"2,024",±682,0.2%,±0.1,"95,928",...,1.7%,±0.4,"59,280","±5,373",2.8%,±0.3,"834,466","±23,524",6.1%,±0.2
16,Two or More Races,"33,181","±3,446",6.2%,±0.6,N,N,N,N,"146,082",...,2.8%,±0.4,"46,359","±3,436",2.2%,±0.2,"330,462","±12,716",2.4%,±0.1
17,Hispanic or Latino,"31,790","±1,004",6.0%,±0.2,"15,070",±911,1.4%,±0.1,"337,941",...,7.0%,±0.5,"190,248","±5,817",9.1%,±0.3,"2,033,344","±20,241",14.8%,±0.1
18,"White alone, Not Hispanic or Latino","349,058","±1,415",65.6%,±0.3,"1,016,354","±1,589",94.9%,±0.2,"5,266,352",...,41.6%,±0.4,"1,760,735","±3,045",84.4%,±0.3,"8,553,329","±11,764",62.1%,±0.1
19,EDUCATIONAL ATTAINMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Less than 9th grade,"10,640","±1,693",2.0%,±0.3,"24,600","±2,742",2.3%,±0.3,"200,778",...,2.2%,±0.4,"28,144","±2,870",1.3%,±0.1,"541,093","±12,970",3.9%,±0.1
21,"9th to 12th grade, no diploma","26,444","±2,293",5.0%,±0.4,"52,524","±3,608",4.9%,±0.3,"584,883",...,4.7%,±0.6,"112,538","±6,979",5.4%,±0.3,"907,828","±16,535",6.6%,±0.1
22,High school graduate (includes equival...,"160,451","±4,824",30.1%,±0.9,"342,506","±7,878",32.0%,±0.7,"2,006,153",...,18.9%,±1.0,"495,871","±11,071",23.8%,±0.5,"3,584,694","±31,965",26.0%,±0.2
23,"Some college, no degree","148,709","±5,567",27.9%,±1.0,"236,725","±6,601",22.1%,±0.6,"1,837,548",...,15.4%,±1.1,"589,770","±10,736",28.3%,±0.5,"2,578,936","±25,114",18.7%,±0.2
24,Associate's degree,"41,699","±2,807",7.8%,±0.5,"99,301","±4,584",9.3%,±0.4,"734,078",...,2.6%,±0.5,"214,821","±7,523",10.3%,±0.4,"1,223,564","±18,026",8.9%,±0.1
25,Bachelor's degree,"89,107","±4,177",16.7%,±0.8,"205,198","±5,909",19.2%,±0.5,"1,496,734",...,26.0%,±1.1,"432,248","±9,138",20.7%,±0.4,"2,851,606","±28,761",20.7%,±0.2
26,Graduate or professional degree,"55,194","±3,489",10.4%,±0.6,"109,807","±4,842",10.3%,±0.5,"769,526",...,30.2%,±0.9,"213,949","±6,588",10.2%,±0.3,"2,082,308","±22,011",15.1%,±0.2
27,High school degree or higher,"495,160","±3,690",93.0%,±0.5,"993,537","±5,405",92.8%,±0.4,"6,844,039",...,93.1%,±0.6,"1,946,659","±9,521",93.3%,±0.4,"12,321,108","±29,233",89.5%,±0.1
28,Bachelor's degree or higher,"144,301","±5,756",27.1%,±1.1,"315,005","±7,234",29.4%,±0.7,"2,266,260",...,56.2%,±0.8,"646,197","±11,510",31.0%,±0.5,"4,933,914","±34,030",35.8%,±0.2
29,POVERTY STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Total Citizens, 18 years and older, fo...","519,019","±2,513",(X),(X),"1,043,005","±2,857",(X),(X),"7,392,393",...,(X),(X),"2,052,201","±7,006",(X),(X),"13,371,194","±26,432",(X),(X)
31,Income in the past 12 months below pov...,"51,051","±4,246",9.8%,±0.8,"114,438","±5,297",11.0%,±0.5,"866,201",...,14.6%,±1.0,"171,099","±9,330",8.3%,±0.4,"1,541,839","±27,715",11.5%,±0.2
32,Income in the past 12 months at or abo...,"467,968","±4,584",90.2%,±0.8,"928,567","±5,834",89.0%,±0.5,"6,526,192",...,85.4%,±1.0,"1,881,102","±9,971",91.7%,±0.4,"11,829,355","±35,046",88.5%,±0.2
33,HOUSEHOLD INCOME (IN 2018 INFLATION-ADJUST...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Median Household Income for Households...,"74,192","±2,305",(X),(X),"55,663","±1,300",(X),(X),"54,729",...,(X),(X),"72,685","±1,043",(X),(X),"69,956",±557,(X),(X)

In [6]:
for column in data.columns:
    if column == "Label": continue
    if "!!Total!!Estimate" not in column:
        data = data.drop(column, axis=1)
data

,Label,Alaska!!Total!!Estimate,Maine!!Total!!Estimate,North Carolina!!Total!!Estimate,Missouri!!Total!!Estimate,Pennsylvania!!Total!!Estimate,Michigan!!Total!!Estimate,Nebraska!!Total!!Estimate,Oregon!!Total!!Estimate,Wyoming!!Total!!Estimate,...,Arkansas!!Total!!Estimate,Delaware!!Total!!Estimate,Minnesota!!Total!!Estimate,Montana!!Total!!Estimate,Arizona!!Total!!Estimate,Florida!!Total!!Estimate,Massachusetts!!Total!!Estimate,District of Columbia!!Total!!Estimate,Utah!!Total!!Estimate,New York!!Total!!Estimate
0,Citizens 18 years and over,"532,244","1,070,661","7,629,700","4,633,370","9,781,212","7,542,878","1,380,260","3,098,171","433,644",...,"2,224,112","720,867","4,106,914","823,668","5,035,771","15,327,815","5,035,804","526,393","2,087,341","13,770,029"
1,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18 to 29 years,"127,476","181,628","1,605,709","950,969","1,928,161","1,573,334","296,186","617,912","86,967",...,"469,906","140,123","817,820","162,487","1,107,241","2,867,965","1,080,377","145,434","567,726","2,924,030"
3,30 to 44 years,"144,647","227,304","1,755,720","1,091,978","2,170,864","1,653,542","337,825","754,771","106,361",...,"521,951","153,037","1,007,885","190,761","1,159,231","3,306,343","1,120,870","165,893","596,259","3,189,035"
4,45 to 64 years,"174,789","388,346","2,604,091","1,561,209","3,380,076","2,621,192","445,198","1,002,016","144,337",...,"729,350","249,503","1,403,438","270,899","1,561,631","5,020,822","1,736,866","131,762","578,946","4,615,032"
5,65 years and over,"85,332","273,383","1,664,180","1,029,214","2,302,111","1,694,810","301,051","723,472","95,979",...,"502,905","178,204","877,771","199,521","1,207,668","4,132,685","1,097,691","83,304","344,410","3,041,932"
6,SEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Male,"279,792","518,367","3,634,888","2,240,784","4,726,343","3,667,806","679,331","1,518,467","219,788",...,"1,074,651","343,826","2,023,293","413,026","2,478,560","7,371,100","2,400,775","245,922","1,041,497","6,565,089"
8,Female,"252,452","552,294","3,994,812","2,392,586","5,054,869","3,875,072","700,929","1,579,704","213,856",...,"1,149,461","377,041","2,083,621","410,642","2,557,211","7,956,715","2,635,029","280,471","1,045,844","7,204,940"
9,RACE AND HISPANIC ORIGIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,White alone,"368,438","1,027,268","5,476,286","3,921,613","8,181,887","6,129,604","1,246,241","2,714,328","404,463",...,"1,772,891","521,934","3,612,605","747,646","4,067,382","11,927,653","4,176,989","240,198","1,878,243","9,479,819"
11,Black or African American alone,"17,519","8,276","1,673,716","514,289","1,013,276","1,007,850","58,693","53,328",N,...,"332,151","158,901","194,296",N,"235,473","2,302,492","337,379","240,843","22,236","2,139,909"
12,Asian alone,"26,468","8,429","142,490","59,828","232,421","154,309","18,750","109,489","2,909",...,"23,033","15,714","141,920","4,509","131,296","350,164","244,395","19,162","41,022","922,184"
13,American Indian and Alaska Native alone,N,N,"89,491",N,"14,872","39,224",N,"36,118",N,...,N,N,"40,584",N,"225,636","44,172",N,N,N,"56,168"
14,Native Hawaiian and Other Pacific Isla...,"4,320",N,"5,707","3,951",N,"2,902",N,"9,176",N,...,"2,668",N,N,N,"11,034","9,437",N,N,"17,875","7,021"
15,Some Other Race alone,"6,980","2,024","95,928","27,155","172,982","57,772","16,792","60,962",N,...,"34,576","6,555","36,479","3,505","211,608","379,968","156,986","9,019","59,280","834,466"
16,Two or More Races,"33,181",N,"146,082","84,168","162,606","151,217","27,502","114,770",N,...,"43,012","13,093","79,970",N,"153,342","313,929","106,038","14,842","46,359","330,462"
17,Hispanic or Latino,"31,790","15,070","337,941","123,751","527,340","264,843","87,039","236,661","32,683",...,"86,138","38,834","124,741","24,492","1,188,723","3,141,934","448,318","36,738","190,248","2,033,344"
18,"White alone, Not Hispanic or Latino","349,058","1,016,354","5,266,352","3,833,132","7,890,171","5,943,602","1,182,496","2,563,656","378,267",...,"1,725,137","495,504","3,537,015","729,822","3,191,082","9,325,209","3,920,473","219,188","1,760,735","8,553,329"
19,EDUCATIONAL ATTAINMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Less than 9th grade,"10,640","24,600","200,778","114,124","249,112","161,150","32,572","58,143","6,797",...,"74,892","16,821","74,789","13,693","158,255","480,480","148,210","11,472","28,144","541,093"
21,"9th to 12th grade, no diploma","26,444","52,524","584,883","330,937","616,418","499,570","68,183","185,531","25,914",...,"183,542","47,602","181,950","43,308","361,342","1,108,062","260,734","24,872","112,538","907,828"
22,High school graduate (includes equival...,"160,451","342,506","2,006,153","1,425,877","3,438,340","2,217,910","364,914","727,912","128,479",...,"770,535","244,349","1,023,146","235,406","1,268,920","4,428,650","1,198,355","99,438","495,871","3,584,694"
23,"Some college, no degree","148,709","236,725","1,837,548","1,146,249","1,792,444","1,950,975","349,519","853,537","120,333",...,"549,241","149,356","951,408","213,870","1,389,701","3,383,383","961,494","81,020","589,770","2,578,936"
24,Associate's degree,"41,699","99,301","734,078","368,097","805,992","689,604","144,797","281,441","46,062",...,"167,399","54,332","469,157","75,647","446,509","1,538,610","370,597","13,643","214,821","1,223,564"
25,Bachelor's degree,"89,107","205,198","1,496,734","787,128","1,798,361","1,279,897","283,910","633,177","67,939",...,"309,602","125,319","955,496","161,452","904,959","2,804,292","1,209,374","137,112","432,248","2,851,606"
26,Graduate or professional degree,"55,194","109,807","769,526","460,958","1,080,545","743,772","136,365","358,430","38,120",...,"168,901","83,088","450,968","80,292","506,085","1,584,338","887,040","158,836","213,949","2,082,308"
27,High school degree or higher,"495,160","993,537","6,844,039","4,188,309","8,915,682","6,882,158","1,279,505","2,854,497","400,933",...,"1,965,678","656,444","3,850,175","766,667","4,516,174","13,739,273","4,626,860","490,049","1,946,659","12,321,108"
28,Bachelor's degree or higher,"144,301","315,005","2,266,260","1,248,086","2,878,906","2,023,669","420,275","991,607","106,059",...,"478,503","208,407","1,406,464","241,744","1,411,044","4,388,630","2,096,414","295,948","646,197","4,933,914"
29,POVERTY STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Total Citizens, 18 years and older, fo...","519,019","1,043,005","7,392,393","4,485,414","9,433,711","7,368,915","1,338,264","3,041,834","422,610",...,"2,150,536","698,953","4,011,388","804,355","4,910,593","14,993,461","4,838,216","497,589","2,052,201","13,371,194"
31,Income in the past 12 months below pov...,"51,051","114,438","866,201","517,093","1,010,716","905,406","130,638","343,849","42,105",...,"318,945","72,431","342,929","97,803","542,438","1,699,386","421,007","72,562","171,099","1,541,839"
32,Income in the past 12 months at or abo...,"467,968","928,567","6,526,192","3,968,321","8,422,995","6,463,509","1,207,626","2,697,985","380,505",...,"1,831,591","626,522","3,668,459","706,552","4,368,155","13,294,075","4,417,209","425,027","1,881,102","11,829,355"
33,HOUSEHOLD INCOME (IN 2018 INFLATION-ADJUST...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Median Household Income for Households...,"74,192","55,663","54,729","54,647","61,150","56,669","60,399","64,276","62,108",...,"47,210","64,723","71,056","55,335","60,836","56,794","80,919","86,510","72,685","69,956"

In [7]:
data = data.dropna()
data.index = np.arange(len(data.index))
data

,Label,Alaska!!Total!!Estimate,Maine!!Total!!Estimate,North Carolina!!Total!!Estimate,Missouri!!Total!!Estimate,Pennsylvania!!Total!!Estimate,Michigan!!Total!!Estimate,Nebraska!!Total!!Estimate,Oregon!!Total!!Estimate,Wyoming!!Total!!Estimate,...,Arkansas!!Total!!Estimate,Delaware!!Total!!Estimate,Minnesota!!Total!!Estimate,Montana!!Total!!Estimate,Arizona!!Total!!Estimate,Florida!!Total!!Estimate,Massachusetts!!Total!!Estimate,District of Columbia!!Total!!Estimate,Utah!!Total!!Estimate,New York!!Total!!Estimate
0,Citizens 18 years and over,"532,244","1,070,661","7,629,700","4,633,370","9,781,212","7,542,878","1,380,260","3,098,171","433,644",...,"2,224,112","720,867","4,106,914","823,668","5,035,771","15,327,815","5,035,804","526,393","2,087,341","13,770,029"
1,18 to 29 years,"127,476","181,628","1,605,709","950,969","1,928,161","1,573,334","296,186","617,912","86,967",...,"469,906","140,123","817,820","162,487","1,107,241","2,867,965","1,080,377","145,434","567,726","2,924,030"
2,30 to 44 years,"144,647","227,304","1,755,720","1,091,978","2,170,864","1,653,542","337,825","754,771","106,361",...,"521,951","153,037","1,007,885","190,761","1,159,231","3,306,343","1,120,870","165,893","596,259","3,189,035"
3,45 to 64 years,"174,789","388,346","2,604,091","1,561,209","3,380,076","2,621,192","445,198","1,002,016","144,337",...,"729,350","249,503","1,403,438","270,899","1,561,631","5,020,822","1,736,866","131,762","578,946","4,615,032"
4,65 years and over,"85,332","273,383","1,664,180","1,029,214","2,302,111","1,694,810","301,051","723,472","95,979",...,"502,905","178,204","877,771","199,521","1,207,668","4,132,685","1,097,691","83,304","344,410","3,041,932"
5,Male,"279,792","518,367","3,634,888","2,240,784","4,726,343","3,667,806","679,331","1,518,467","219,788",...,"1,074,651","343,826","2,023,293","413,026","2,478,560","7,371,100","2,400,775","245,922","1,041,497","6,565,089"
6,Female,"252,452","552,294","3,994,812","2,392,586","5,054,869","3,875,072","700,929","1,579,704","213,856",...,"1,149,461","377,041","2,083,621","410,642","2,557,211","7,956,715","2,635,029","280,471","1,045,844","7,204,940"
7,White alone,"368,438","1,027,268","5,476,286","3,921,613","8,181,887","6,129,604","1,246,241","2,714,328","404,463",...,"1,772,891","521,934","3,612,605","747,646","4,067,382","11,927,653","4,176,989","240,198","1,878,243","9,479,819"
8,Black or African American alone,"17,519","8,276","1,673,716","514,289","1,013,276","1,007,850","58,693","53,328",N,...,"332,151","158,901","194,296",N,"235,473","2,302,492","337,379","240,843","22,236","2,139,909"
9,Asian alone,"26,468","8,429","142,490","59,828","232,421","154,309","18,750","109,489","2,909",...,"23,033","15,714","141,920","4,509","131,296","350,164","244,395","19,162","41,022","922,184"
10,American Indian and Alaska Native alone,N,N,"89,491",N,"14,872","39,224",N,"36,118",N,...,N,N,"40,584",N,"225,636","44,172",N,N,N,"56,168"
11,Native Hawaiian and Other Pacific Isla...,"4,320",N,"5,707","3,951",N,"2,902",N,"9,176",N,...,"2,668",N,N,N,"11,034","9,437",N,N,"17,875","7,021"
12,Some Other Race alone,"6,980","2,024","95,928","27,155","172,982","57,772","16,792","60,962",N,...,"34,576","6,555","36,479","3,505","211,608","379,968","156,986","9,019","59,280","834,466"
13,Two or More Races,"33,181",N,"146,082","84,168","162,606","151,217","27,502","114,770",N,...,"43,012","13,093","79,970",N,"153,342","313,929","106,038","14,842","46,359","330,462"
14,Hispanic or Latino,"31,790","15,070","337,941","123,751","527,340","264,843","87,039","236,661","32,683",...,"86,138","38,834","124,741","24,492","1,188,723","3,141,934","448,318","36,738","190,248","2,033,344"
15,"White alone, Not Hispanic or Latino","349,058","1,016,354","5,266,352","3,833,132","7,890,171","5,943,602","1,182,496","2,563,656","378,267",...,"1,725,137","495,504","3,537,015","729,822","3,191,082","9,325,209","3,920,473","219,188","1,760,735","8,553,329"
16,Less than 9th grade,"10,640","24,600","200,778","114,124","249,112","161,150","32,572","58,143","6,797",...,"74,892","16,821","74,789","13,693","158,255","480,480","148,210","11,472","28,144","541,093"
17,"9th to 12th grade, no diploma","26,444","52,524","584,883","330,937","616,418","499,570","68,183","185,531","25,914",...,"183,542","47,602","181,950","43,308","361,342","1,108,062","260,734","24,872","112,538","907,828"
18,High school graduate (includes equival...,"160,451","342,506","2,006,153","1,425,877","3,438,340","2,217,910","364,914","727,912","128,479",...,"770,535","244,349","1,023,146","235,406","1,268,920","4,428,650","1,198,355","99,438","495,871","3,584,694"
19,"Some college, no degree","148,709","236,725","1,837,548","1,146,249","1,792,444","1,950,975","349,519","853,537","120,333",...,"549,241","149,356","951,408","213,870","1,389,701","3,383,383","961,494","81,020","589,770","2,578,936"
20,Associate's degree,"41,699","99,301","734,078","368,097","805,992","689,604","144,797","281,441","46,062",...,"167,399","54,332","469,157","75,647","446,509","1,538,610","370,597","13,643","214,821","1,223,564"
21,Bachelor's degree,"89,107","205,198","1,496,734","787,128","1,798,361","1,279,897","283,910","633,177","67,939",...,"309,602","125,319","955,496","161,452","904,959","2,804,292","1,209,374","137,112","432,248","2,851,606"
22,Graduate or professional degree,"55,194","109,807","769,526","460,958","1,080,545","743,772","136,365","358,430","38,120",...,"168,901","83,088","450,968","80,292","506,085","1,584,338","887,040","158,836","213,949","2,082,308"
23,High school degree or higher,"495,160","993,537","6,844,039","4,188,309","8,915,682","6,882,158","1,279,505","2,854,497","400,933",...,"1,965,678","656,444","3,850,175","766,667","4,516,174","13,739,273","4,626,860","490,049","1,946,659","12,321,108"
24,Bachelor's degree or higher,"144,301","315,005","2,266,260","1,248,086","2,878,906","2,023,669","420,275","991,607","106,059",...,"478,503","208,407","1,406,464","241,744","1,411,044","4,388,630","2,096,414","295,948","646,197","4,933,914"
25,"Total Citizens, 18 years and older, fo...","519,019","1,043,005","7,392,393","4,485,414","9,433,711","7,368,915","1,338,264","3,041,834","422,610",...,"2,150,536","698,953","4,011,388","804,355","4,910,593","14,993,461","4,838,216","497,589","2,052,201","13,371,194"
26,Income in the past 12 months below pov...,"51,051","114,438","866,201","517,093","1,010,716","905,406","130,638","343,849","42,105",...,"318,945","72,431","342,929","97,803","542,438","1,699,386","421,007","72,562","171,099","1,541,839"
27,Income in the past 12 months at or abo...,"467,968","928,567","6,526,192","3,968,321","8,422,995","6,463,509","1,207,626","2,697,985","380,505",...,"1,831,591","626,522","3,668,459","706,552","4,368,155","13,294,075","4,417,209","425,027","1,881,102","11,829,355"
28,Median Household Income for Households...,"74,192","55,663","54,729","54,647","61,150","56,669","60,399","64,276","62,108",...,"47,210","64,723","71,056","55,335","60,836","56,794","80,919","86,510","72,685","69,956"

In [8]:
# Renaming columns
data.columns = (data.columns.str.replace("!!Total!!Estimate", ""))
data = alphabetize(data)

,Label,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Citizens 18 years and over,"3,712,212","532,244","5,035,771","2,224,112","25,838,830","4,151,040","2,614,365","720,867","526,393",...,"647,089","5,075,166","18,502,334","2,087,341","500,274","6,213,686","5,355,539","1,431,158","4,401,754","433,644"
1,18 to 29 years,"768,804","127,476","1,107,241","469,906","6,028,864","915,609","520,431","140,123","145,434",...,"135,924","1,056,534","4,394,424","567,726","100,387","1,314,205","1,116,310","267,223","888,479","86,967"
2,30 to 44 years,"858,792","144,647","1,159,231","521,951","6,358,182","1,102,183","552,963","153,037","165,893",...,"154,204","1,191,965","4,834,880","596,259","103,384","1,503,106","1,346,421","314,761","1,006,927","106,361"
3,45 to 64 years,"1,259,953","174,789","1,561,631","729,350","8,244,326","1,342,591","947,195","249,503","131,762",...,"211,141","1,730,652","5,912,721","578,946","173,821","2,112,109","1,760,980","489,218","1,528,396","144,337"
4,65 years and over,"824,663","85,332","1,207,668","502,905","5,207,458","790,657","593,776","178,204","83,304",...,"145,820","1,096,015","3,360,309","344,410","122,682","1,284,266","1,131,828","359,956","977,952","95,979"
5,Male,"1,763,395","279,792","2,478,560","1,074,651","12,693,335","2,073,626","1,252,484","343,826","245,922",...,"323,519","2,427,806","9,038,806","1,041,497","244,517","3,015,598","2,655,643","701,390","2,162,711","219,788"
6,Female,"1,948,817","252,452","2,557,211","1,149,461","13,145,495","2,077,414","1,361,881","377,041","280,471",...,"323,570","2,647,360","9,463,528","1,045,844","255,757","3,198,088","2,699,896","729,768","2,239,043","213,856"
7,White alone,"2,607,033","368,438","4,067,382","1,772,891","16,427,059","3,612,937","2,109,655","521,934","240,198",...,"573,199","4,067,694","14,047,850","1,878,243","477,697","4,399,355","4,328,981","1,346,378","3,909,624","404,463"
8,Black or African American alone,"979,390","17,519","235,473","332,151","1,733,938","165,359","265,142","158,901","240,843",...,"7,602","830,612","2,483,006","22,236","4,621","1,222,486","191,840","54,308","252,844",N
9,Asian alone,"30,399","26,468","131,296","23,033","3,637,615","99,021","81,519","15,714","19,162",...,"4,301","57,533","705,534","41,022","6,816","320,693","364,052","7,413","82,724","2,909"
10,American Indian and Alaska Native alone,N,N,"225,636",N,"211,862","42,763","5,855",N,N,...,N,N,"97,576",N,N,"16,173","69,554",N,N,N
11,Native Hawaiian and Other Pacific Isla...,N,"4,320","11,034","2,668","106,796",N,N,N,N,...,N,N,"15,341","17,875",N,N,"33,073",N,N,N
12,Some Other Race alone,"22,308","6,980","211,608","34,576","2,664,272","106,140","95,670","6,555","9,019",...,"2,976","28,498","764,568","59,280","1,688","80,450","128,422","3,105","51,146",N
13,Two or More Races,"54,771","33,181","153,342","43,012","1,057,288","117,945","55,934","13,093","14,842",...,N,"72,307","388,459","46,359",N,"169,837","239,617","17,292","66,873",N
14,Hispanic or Latino,"80,325","31,790","1,188,723","86,138","7,863,415","666,340","321,257","38,834","36,738",...,"16,770","125,024","5,627,836","190,248","8,387","343,754","409,859","15,663","183,767","32,683"
15,"White alone, Not Hispanic or Latino","2,554,006","349,058","3,191,082","1,725,137","11,748,576","3,109,968","1,919,416","495,504","219,188",...,"562,090","3,979,945","9,394,473","1,760,735","471,163","4,175,696","4,092,643","1,334,652","3,789,533","378,267"
16,Less than 9th grade,"118,452","10,640","158,255","74,892","1,147,037","76,192","66,360","16,821","11,472",...,"14,171","175,063","745,191","28,144","8,442","163,575","100,582","51,324","85,995","6,797"
17,"9th to 12th grade, no diploma","361,105","26,444","361,342","183,542","1,655,142","209,454","140,171","47,602","24,872",...,"37,075","402,952","1,399,208","112,538","24,270","386,258","277,579","125,139","239,610","25,914"
18,High school graduate (includes equival...,"1,168,042","160,451","1,268,920","770,535","5,700,939","916,890","715,344","244,349","99,438",...,"198,743","1,645,147","4,965,575","495,871","148,257","1,573,621","1,245,168","567,372","1,362,764","128,479"
19,"Some college, no degree","886,600","148,709","1,389,701","549,241","6,611,903","969,786","525,586","149,356","81,020",...,"144,419","1,189,177","4,711,885","589,770","103,584","1,360,002","1,364,019","301,695","1,020,683","120,333"
20,Associate's degree,"310,804","41,699","446,509","167,399","2,158,366","340,812","199,028","54,332","13,643",...,"76,351","373,922","1,373,120","214,821","39,333","472,086","558,284","102,113","463,579","46,062"
21,Bachelor's degree,"558,690","89,107","904,959","309,602","5,507,471","1,047,679","554,968","125,319","137,112",...,"125,006","831,536","3,534,680","432,248","109,047","1,322,125","1,165,008","175,667","822,580","67,939"
22,Graduate or professional degree,"308,519","55,194","506,085","168,901","3,057,972","590,227","412,908","83,088","158,836",...,"51,324","457,369","1,772,675","213,949","67,341","936,019","644,899","107,848","406,543","38,120"
23,High school degree or higher,"3,232,655","495,160","4,516,174","1,965,678","23,036,651","3,865,394","2,407,834","656,444","490,049",...,"595,843","4,497,151","16,357,935","1,946,659","467,562","5,663,853","4,977,378","1,254,695","4,076,149","400,933"
24,Bachelor's degree or higher,"867,209","144,301","1,411,044","478,503","8,565,443","1,637,906","967,876","208,407","295,948",...,"176,330","1,288,905","5,307,355","646,197","176,388","2,258,144","1,809,907","283,515","1,229,123","106,059"
25,"Total Citizens, 18 years and older, fo...","3,610,653","519,019","4,910,593","2,150,536","25,279,607","4,049,465","2,521,646","698,953","497,589",...,"623,323","4,939,053","18,008,534","2,052,201","478,729","5,997,036","5,254,428","1,389,017","4,280,523","422,610"
26,Income in the past 12 months below pov...,"524,972","51,051","542,438","318,945","2,587,283","347,857","224,748","72,431","72,562",...,"73,236","638,676","2,057,713","171,099","51,013","574,018","477,144","222,590","425,134","42,105"
27,Income in the past 12 months at or abo...,"3,085,681","467,968","4,368,155","1,831,591","22,692,324","3,701,608","2,296,898","626,522","425,027",...,"550,087","4,300,377","15,950,821","1,881,102","427,716","5,423,018","4,777,284","1,166,427","3,855,389","380,505"
28,Median Household Income for Households...,"50,145","74,192","60,836","47,210","79,296","73,409","77,772","64,723","86,510",...,"56,576","52,798","62,781","72,685","60,813","73,304","74,810","44,179","61,023","62,108"

In [9]:
# converting all strings to float (if they arent a number they become 0)
for i in range(1, len(data.columns)):
    col = data.iloc[:, i].astype(str).str.replace('\D+', '').apply(p2f)
    data[data.columns[i]] = col

#removing as many 0 values as I can easily
data = data[data["Alabama"] > 0]
data

,Label,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Citizens 18 years and over,3712212.0,532244.0,5035771.0,2224112.0,25838830.0,4151040.0,2614365.0,720867.0,526393.0,...,647089.0,5075166.0,18502334.0,2087341.0,500274.0,6213686.0,5355539.0,1431158.0,4401754.0,433644.0
1,18 to 29 years,768804.0,127476.0,1107241.0,469906.0,6028864.0,915609.0,520431.0,140123.0,145434.0,...,135924.0,1056534.0,4394424.0,567726.0,100387.0,1314205.0,1116310.0,267223.0,888479.0,86967.0
2,30 to 44 years,858792.0,144647.0,1159231.0,521951.0,6358182.0,1102183.0,552963.0,153037.0,165893.0,...,154204.0,1191965.0,4834880.0,596259.0,103384.0,1503106.0,1346421.0,314761.0,1006927.0,106361.0
3,45 to 64 years,1259953.0,174789.0,1561631.0,729350.0,8244326.0,1342591.0,947195.0,249503.0,131762.0,...,211141.0,1730652.0,5912721.0,578946.0,173821.0,2112109.0,1760980.0,489218.0,1528396.0,144337.0
4,65 years and over,824663.0,85332.0,1207668.0,502905.0,5207458.0,790657.0,593776.0,178204.0,83304.0,...,145820.0,1096015.0,3360309.0,344410.0,122682.0,1284266.0,1131828.0,359956.0,977952.0,95979.0
5,Male,1763395.0,279792.0,2478560.0,1074651.0,12693335.0,2073626.0,1252484.0,343826.0,245922.0,...,323519.0,2427806.0,9038806.0,1041497.0,244517.0,3015598.0,2655643.0,701390.0,2162711.0,219788.0
6,Female,1948817.0,252452.0,2557211.0,1149461.0,13145495.0,2077414.0,1361881.0,377041.0,280471.0,...,323570.0,2647360.0,9463528.0,1045844.0,255757.0,3198088.0,2699896.0,729768.0,2239043.0,213856.0
7,White alone,2607033.0,368438.0,4067382.0,1772891.0,16427059.0,3612937.0,2109655.0,521934.0,240198.0,...,573199.0,4067694.0,14047850.0,1878243.0,477697.0,4399355.0,4328981.0,1346378.0,3909624.0,404463.0
8,Black or African American alone,979390.0,17519.0,235473.0,332151.0,1733938.0,165359.0,265142.0,158901.0,240843.0,...,7602.0,830612.0,2483006.0,22236.0,4621.0,1222486.0,191840.0,54308.0,252844.0,0.0
9,Asian alone,30399.0,26468.0,131296.0,23033.0,3637615.0,99021.0,81519.0,15714.0,19162.0,...,4301.0,57533.0,705534.0,41022.0,6816.0,320693.0,364052.0,7413.0,82724.0,2909.0
12,Some Other Race alone,22308.0,6980.0,211608.0,34576.0,2664272.0,106140.0,95670.0,6555.0,9019.0,...,2976.0,28498.0,764568.0,59280.0,1688.0,80450.0,128422.0,3105.0,51146.0,0.0
13,Two or More Races,54771.0,33181.0,153342.0,43012.0,1057288.0,117945.0,55934.0,13093.0,14842.0,...,0.0,72307.0,388459.0,46359.0,0.0,169837.0,239617.0,17292.0,66873.0,0.0
14,Hispanic or Latino,80325.0,31790.0,1188723.0,86138.0,7863415.0,666340.0,321257.0,38834.0,36738.0,...,16770.0,125024.0,5627836.0,190248.0,8387.0,343754.0,409859.0,15663.0,183767.0,32683.0
15,"White alone, Not Hispanic or Latino",2554006.0,349058.0,3191082.0,1725137.0,11748576.0,3109968.0,1919416.0,495504.0,219188.0,...,562090.0,3979945.0,9394473.0,1760735.0,471163.0,4175696.0,4092643.0,1334652.0,3789533.0,378267.0
16,Less than 9th grade,118452.0,10640.0,158255.0,74892.0,1147037.0,76192.0,66360.0,16821.0,11472.0,...,14171.0,175063.0,745191.0,28144.0,8442.0,163575.0,100582.0,51324.0,85995.0,6797.0
17,"9th to 12th grade, no diploma",361105.0,26444.0,361342.0,183542.0,1655142.0,209454.0,140171.0,47602.0,24872.0,...,37075.0,402952.0,1399208.0,112538.0,24270.0,386258.0,277579.0,125139.0,239610.0,25914.0
18,High school graduate (includes equival...,1168042.0,160451.0,1268920.0,770535.0,5700939.0,916890.0,715344.0,244349.0,99438.0,...,198743.0,1645147.0,4965575.0,495871.0,148257.0,1573621.0,1245168.0,567372.0,1362764.0,128479.0
19,"Some college, no degree",886600.0,148709.0,1389701.0,549241.0,6611903.0,969786.0,525586.0,149356.0,81020.0,...,144419.0,1189177.0,4711885.0,589770.0,103584.0,1360002.0,1364019.0,301695.0,1020683.0,120333.0
20,Associate's degree,310804.0,41699.0,446509.0,167399.0,2158366.0,340812.0,199028.0,54332.0,13643.0,...,76351.0,373922.0,1373120.0,214821.0,39333.0,472086.0,558284.0,102113.0,463579.0,46062.0
21,Bachelor's degree,558690.0,89107.0,904959.0,309602.0,5507471.0,1047679.0,554968.0,125319.0,137112.0,...,125006.0,831536.0,3534680.0,432248.0,109047.0,1322125.0,1165008.0,175667.0,822580.0,67939.0
22,Graduate or professional degree,308519.0,55194.0,506085.0,168901.0,3057972.0,590227.0,412908.0,83088.0,158836.0,...,51324.0,457369.0,1772675.0,213949.0,67341.0,936019.0,644899.0,107848.0,406543.0,38120.0
23,High school degree or higher,3232655.0,495160.0,4516174.0,1965678.0,23036651.0,3865394.0,2407834.0,656444.0,490049.0,...,595843.0,4497151.0,16357935.0,1946659.0,467562.0,5663853.0,4977378.0,1254695.0,4076149.0,400933.0
24,Bachelor's degree or higher,867209.0,144301.0,1411044.0,478503.0,8565443.0,1637906.0,967876.0,208407.0,295948.0,...,176330.0,1288905.0,5307355.0,646197.0,176388.0,2258144.0,1809907.0,283515.0,1229123.0,106059.0
25,"Total Citizens, 18 years and older, fo...",3610653.0,519019.0,4910593.0,2150536.0,25279607.0,4049465.0,2521646.0,698953.0,497589.0,...,623323.0,4939053.0,18008534.0,2052201.0,478729.0,5997036.0,5254428.0,1389017.0,4280523.0,422610.0
26,Income in the past 12 months below pov...,524972.0,51051.0,542438.0,318945.0,2587283.0,347857.0,224748.0,72431.0,72562.0,...,73236.0,638676.0,2057713.0,171099.0,51013.0,574018.0,477144.0,222590.0,425134.0,42105.0
27,Income in the past 12 months at or abo...,3085681.0,467968.0,4368155.0,1831591.0,22692324.0,3701608.0,2296898.0,626522.0,425027.0,...,550087.0,4300377.0,15950821.0,1881102.0,427716.0,5423018.0,4777284.0,1166427.0,3855389.0,380505.0
28,Median Household Income for Households...,50145.0,74192.0,60836.0,47210.0,79296.0,73409.0,77772.0,64723.0,86510.0,...,56576.0,52798.0,62781.0,72685.0,60813.0,73304.0,74810.0,44179.0,61023.0,62108.0

In [10]:
#discarding PR for electoral vote file
data = data.drop('Puerto Rico', axis = 1)

In [11]:
#reindexing again to organize 
data.index = np.arange(len(data.index))

In [12]:
#copies comes in because now I can create the expected array rn
copies = data.drop("Label", axis = 1)

#expected array
expected = copies.sum(axis=1) / copies.sum(axis = 1)[0] * 538

In [13]:
#now splitting up data on a per-capita basis
total_pop=data.iloc[0]

for i in range(1, len(data.columns)):
    col = data.iloc[:, i] / total_pop[i]
    data[data.columns[i]] = col

data

,Label,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Citizens 18 years and over,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,18 to 29 years,0.207101,0.239507,0.219875,0.211278,0.233326,0.220573,0.199066,0.194381,0.276284,...,0.210055,0.208177,0.237506,0.271985,0.200664,0.211502,0.208440,0.186718,0.201847,0.200549
2,30 to 44 years,0.231342,0.271768,0.230199,0.234678,0.246071,0.265520,0.211509,0.212296,0.315150,...,0.238304,0.234862,0.261312,0.285655,0.206655,0.241902,0.251407,0.219934,0.228756,0.245273
3,45 to 64 years,0.339408,0.328400,0.310108,0.327929,0.319067,0.323435,0.362304,0.346115,0.250311,...,0.326294,0.341004,0.319566,0.277361,0.347452,0.339912,0.328815,0.341834,0.347224,0.332847
4,65 years and over,0.222149,0.160325,0.239818,0.226115,0.201536,0.190472,0.227121,0.247208,0.158254,...,0.225348,0.215956,0.181615,0.164999,0.245230,0.206683,0.211338,0.251514,0.222173,0.221331
5,Male,0.475025,0.525684,0.492191,0.483182,0.491250,0.499544,0.479078,0.476962,0.467183,...,0.499961,0.478370,0.488522,0.498959,0.488766,0.485315,0.495868,0.490086,0.491329,0.506840
6,Female,0.524975,0.474316,0.507809,0.516818,0.508750,0.500456,0.520922,0.523038,0.532817,...,0.500039,0.521630,0.511478,0.501041,0.511234,0.514685,0.504132,0.509914,0.508671,0.493160
7,White alone,0.702286,0.692235,0.807698,0.797123,0.635751,0.870369,0.806947,0.724036,0.456309,...,0.885812,0.801490,0.759247,0.899826,0.954871,0.708011,0.808318,0.940761,0.888197,0.932707
8,Black or African American alone,0.263829,0.032915,0.046760,0.149341,0.067106,0.039836,0.101417,0.220430,0.457535,...,0.011748,0.163662,0.134200,0.010653,0.009237,0.196741,0.035821,0.037947,0.057442,0.000000
9,Asian alone,0.008189,0.049729,0.026073,0.010356,0.140781,0.023855,0.031181,0.021799,0.036402,...,0.006647,0.011336,0.038132,0.019653,0.013625,0.051611,0.067977,0.005180,0.018793,0.006708
10,Some Other Race alone,0.006009,0.013114,0.042021,0.015546,0.103111,0.025569,0.036594,0.009093,0.017134,...,0.004599,0.005615,0.041323,0.028400,0.003374,0.012947,0.023979,0.002170,0.011619,0.000000
11,Two or More Races,0.014754,0.062342,0.030451,0.019339,0.040919,0.028413,0.021395,0.018163,0.028196,...,0.000000,0.014247,0.020995,0.022210,0.000000,0.027333,0.044742,0.012083,0.015192,0.000000
12,Hispanic or Latino,0.021638,0.059728,0.236056,0.038729,0.304326,0.160524,0.122881,0.053871,0.069792,...,0.025916,0.024634,0.304169,0.091144,0.016765,0.055322,0.076530,0.010944,0.041749,0.075368
13,"White alone, Not Hispanic or Latino",0.688001,0.655823,0.633683,0.775652,0.454687,0.749202,0.734181,0.687372,0.416396,...,0.868644,0.784200,0.507745,0.843530,0.941810,0.672016,0.764189,0.932568,0.860914,0.872298
14,Less than 9th grade,0.031909,0.019991,0.031426,0.033673,0.044392,0.018355,0.025383,0.023334,0.021794,...,0.021900,0.034494,0.040276,0.013483,0.016875,0.026325,0.018781,0.035862,0.019537,0.015674
15,"9th to 12th grade, no diploma",0.097275,0.049684,0.071755,0.082524,0.064056,0.050458,0.053616,0.066034,0.047250,...,0.057295,0.079397,0.075623,0.053915,0.048513,0.062162,0.051830,0.087439,0.054435,0.059759
16,High school graduate (includes equival...,0.314649,0.301461,0.251981,0.346446,0.220635,0.220882,0.273621,0.338965,0.188904,...,0.307134,0.324156,0.268376,0.237561,0.296352,0.253251,0.232501,0.396443,0.309596,0.296278
17,"Some college, no degree",0.238833,0.279400,0.275966,0.246948,0.255890,0.233625,0.201038,0.207189,0.153915,...,0.223183,0.234313,0.254664,0.282546,0.207055,0.218872,0.254693,0.210805,0.231881,0.277493
18,Associate's degree,0.083725,0.078346,0.088667,0.075266,0.083532,0.082103,0.076129,0.075370,0.025918,...,0.117991,0.073677,0.074213,0.102916,0.078623,0.075975,0.104244,0.071350,0.105317,0.106221
19,Bachelor's degree,0.150501,0.167418,0.179706,0.139203,0.213147,0.252390,0.212276,0.173845,0.260475,...,0.193182,0.163844,0.191040,0.207081,0.217975,0.212776,0.217533,0.122745,0.186876,0.156670
20,Graduate or professional degree,0.083109,0.103701,0.100498,0.075941,0.118348,0.142188,0.157938,0.115261,0.301744,...,0.079315,0.090119,0.095808,0.102498,0.134608,0.150638,0.120417,0.075357,0.092359,0.087906
21,High school degree or higher,0.870816,0.930325,0.896819,0.883804,0.891552,0.931187,0.921001,0.910631,0.930957,...,0.920805,0.886109,0.884101,0.932602,0.934612,0.911513,0.929389,0.876699,0.926028,0.924567
22,Bachelor's degree or higher,0.233610,0.271118,0.280204,0.215143,0.331495,0.394577,0.370215,0.289106,0.562219,...,0.272497,0.253963,0.286848,0.309579,0.352583,0.363415,0.337950,0.198102,0.279235,0.244576
23,"Total Citizens, 18 years and older, fo...",0.972642,0.975152,0.975142,0.966919,0.978357,0.975530,0.964535,0.969600,0.945280,...,0.963272,0.973181,0.973311,0.983165,0.956934,0.965133,0.981120,0.970555,0.972458,0.974555
24,Income in the past 12 months below pov...,0.141418,0.095917,0.107717,0.143403,0.100132,0.083800,0.085967,0.100478,0.137848,...,0.113178,0.125843,0.111214,0.081970,0.101970,0.092380,0.089094,0.155531,0.096583,0.097096
25,Income in the past 12 months at or abo...,0.831224,0.879236,0.867425,0.823516,0.878226,0.891730,0.878568,0.869123,0.807433,...,0.850095,0.847337,0.862098,0.901195,0.854963,0.872754,0.892027,0.815023,0.875876,0.877459
26,Median Household Income for Households...,0.013508,0.139395,0.012081,0.021226,0.003069,0.017684,0.029748,0.089785,0.164345,...,0.087432,0.010403,0.003393,0.034822,0.121559,0.011797,0.013969,0.030869,0.013863,0.143223

In [14]:
electorals = pd.read_csv("Data/state_data")
diaspora = electorals["E.C. Votes"] 

for i in range(1, len(data.columns)):
    col = data.iloc[:, i] * diaspora[i-1]
    data[data.columns[i]] = col
data

,Label,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Citizens 18 years and over,9.000000,3.000000,11.000000,6.000000,55.000000,9.000000,7.000000,3.000000,3.000000,...,3.000000,11.000000,38.000000,6.000000,3.000000,13.000000,12.000000,5.000000,10.000000,3.000000
1,18 to 29 years,1.863912,0.718520,2.418627,1.267668,12.832915,1.985161,1.393462,0.583144,0.828852,...,0.630164,2.289950,9.025246,1.631912,0.601992,2.749522,2.501283,0.933590,2.018466,0.601648
2,30 to 44 years,2.082082,0.815305,2.532192,1.408070,13.533895,2.389678,1.480566,0.636887,0.945451,...,0.714912,2.583485,9.929852,1.713929,0.619964,3.144732,3.016886,1.099672,2.287559,0.735818
3,45 to 64 years,3.054668,0.985200,3.411184,1.967572,17.548702,2.910914,2.536128,1.038345,0.750933,...,0.978881,3.751044,12.143516,1.664163,1.042355,4.418861,3.945777,1.709168,3.472243,0.998540
4,65 years and over,1.999338,0.480975,2.637997,1.356690,11.084488,1.714248,1.589844,0.741624,0.474763,...,0.676043,2.375521,6.901386,0.989996,0.735689,2.686885,2.536054,1.257569,2.221733,0.663994
5,Male,4.275229,1.577051,5.414098,2.899092,27.018771,4.495894,3.353544,1.430885,1.401550,...,1.499882,5.262067,18.563854,2.993752,1.466298,6.309101,5.950422,2.450428,4.913294,1.520519
6,Female,4.724771,1.422949,5.585902,3.100908,27.981229,4.504106,3.646456,1.569115,1.598450,...,1.500118,5.737933,19.436146,3.006248,1.533702,6.690899,6.049578,2.549572,5.086706,1.479481
7,White alone,6.320570,2.076705,8.884678,4.782738,34.966299,7.833322,5.648632,2.172109,1.368928,...,2.657435,8.816388,28.851403,5.398954,2.864612,9.204137,9.699821,4.703806,8.881968,2.798122
8,Black or African American alone,2.374463,0.098746,0.514361,0.896046,3.690825,0.358520,0.709922,0.661291,1.372604,...,0.035244,1.800282,5.099585,0.063917,0.027711,2.557631,0.429850,0.189734,0.574416,0.000000
9,Asian alone,0.073700,0.149187,0.286799,0.062136,7.742952,0.214691,0.218268,0.065396,0.109207,...,0.019940,0.124698,1.449022,0.117917,0.040874,0.670940,0.815721,0.025899,0.187934,0.020125
10,Some Other Race alone,0.054084,0.039343,0.462231,0.093276,5.671114,0.230125,0.256158,0.027280,0.051401,...,0.013797,0.061767,1.570266,0.170399,0.010122,0.168314,0.287751,0.010848,0.116195,0.000000
11,Two or More Races,0.132788,0.187025,0.334956,0.116034,2.250521,0.255720,0.149764,0.054489,0.084587,...,0.000000,0.156719,0.797815,0.133258,0.000000,0.355325,0.536903,0.060413,0.151924,0.000000
12,Hispanic or Latino,0.194742,0.179185,2.596614,0.232375,16.737903,1.444713,0.860170,0.161614,0.209376,...,0.077748,0.270979,11.558421,0.546862,0.050294,0.719187,0.918359,0.054721,0.417486,0.226105
13,"White alone, Not Hispanic or Latino",6.192010,1.967470,6.970512,4.653912,25.007776,6.742819,5.139264,2.062117,1.249188,...,2.605932,8.626200,19.294321,5.061181,2.825430,8.736207,9.170266,4.662839,8.609143,2.616895
14,Less than 9th grade,0.287179,0.059972,0.345688,0.202037,2.441559,0.165194,0.177680,0.070003,0.065381,...,0.065699,0.379434,1.530470,0.080899,0.050624,0.342224,0.225371,0.179309,0.195365,0.047022
15,"9th to 12th grade, no diploma",0.875474,0.149052,0.789306,0.495142,3.523101,0.454124,0.375310,0.198103,0.141750,...,0.171885,0.873365,2.873686,0.323487,0.145540,0.808112,0.621963,0.437195,0.544351,0.179276
16,High school graduate (includes equival...,2.831837,0.904384,2.771794,2.078677,12.134901,1.987938,1.915344,1.016896,0.566713,...,0.921402,3.565719,10.198273,1.425367,0.889055,3.292261,2.790012,1.982213,3.095957,0.888833
17,"Some college, no degree",2.149500,0.838200,3.035625,1.481691,14.073960,2.102623,1.407264,0.621568,0.461746,...,0.669548,2.577442,9.677246,1.695276,0.621164,2.845336,3.056318,1.054024,2.318810,0.832478
18,Associate's degree,0.753523,0.235037,0.975342,0.451593,4.594253,0.738925,0.532900,0.226111,0.077754,...,0.353974,0.810445,2.820107,0.617497,0.235869,0.987678,1.250931,0.356750,1.053169,0.318662
19,Bachelor's degree,1.354505,0.502253,1.976768,0.835215,11.723089,2.271506,1.485935,0.521534,0.781424,...,0.579546,1.802285,7.259508,1.242484,0.653924,2.766092,2.610399,0.613723,1.868755,0.470010
20,Graduate or professional degree,0.747983,0.311102,1.105478,0.455645,6.509136,1.279690,1.105567,0.345784,0.905232,...,0.237946,0.991309,3.640711,0.614990,0.403825,1.958298,1.445006,0.376786,0.923593,0.263719
21,High school degree or higher,7.837347,2.790976,9.865007,5.302821,49.035340,8.380682,6.447010,2.731894,2.792870,...,2.762416,9.747201,33.595844,5.595614,2.803835,11.849664,11.152666,4.383496,9.260284,2.773701
22,Bachelor's degree or higher,2.102488,0.813354,3.082246,1.290860,18.232225,3.551195,2.591502,0.867318,1.686656,...,0.817492,2.793594,10.900219,1.857474,1.057748,4.724389,4.055406,0.990509,2.792348,0.733729
23,"Total Citizens, 18 years and older, fo...",8.753777,2.925457,10.726565,5.801514,53.809649,8.779772,6.751744,2.908801,2.835841,...,2.889817,10.704986,36.985836,5.898991,2.870801,12.546734,11.773444,4.852773,9.724585,2.923665
24,Income in the past 12 months below pov...,1.272758,0.287750,1.184887,0.860420,5.507237,0.754200,0.601766,0.301433,0.413543,...,0.339533,1.384277,4.226121,0.491819,0.305910,1.200935,1.069123,0.777657,0.965829,0.291287
25,Income in the past 12 months at or abo...,7.481019,2.637708,9.541678,4.941094,48.302412,8.025572,6.149978,2.607369,2.422299,...,2.550284,9.320709,32.759716,5.407172,2.564890,11.345799,10.704321,4.075116,8.758756,2.632378
26,Median Household Income for Households...,0.121573,0.418184,0.132888,0.127359,0.168788,0.159160,0.208236,0.269355,0.493035,...,0.262295,0.114435,0.128939,0.208931,0.364678,0.153363,0.167625,0.154347,0.138633,0.429670

In [16]:
#isolate the list of states to perform arithmetic on
states = list(data)
states.remove("Label")
data[states]

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Expected
0,9.000000,3.000000,11.000000,6.000000,55.000000,9.000000,7.000000,3.000000,3.000000,29.000000,...,11.000000,38.000000,6.000000,3.000000,13.000000,12.000000,5.000000,10.000000,3.000000,538.000000
1,1.863912,0.718520,2.418627,1.267668,12.832915,1.985161,1.393462,0.583144,0.828852,5.426147,...,2.289950,9.025246,1.631912,0.601992,2.749522,2.501283,0.933590,2.018466,0.601648,114.560540
2,2.082082,0.815305,2.532192,1.408070,13.533895,2.389678,1.480566,0.636887,0.945451,6.255552,...,2.583485,9.929852,1.713929,0.619964,3.144732,3.016886,1.099672,2.287559,0.735818,127.556378
3,3.054668,0.985200,3.411184,1.967572,17.548702,2.910914,2.536128,1.038345,0.750933,9.499321,...,3.751044,12.143516,1.664163,1.042355,4.418861,3.945777,1.709168,3.472243,0.998540,179.212749
4,1.999338,0.480975,2.637997,1.356690,11.084488,1.714248,1.589844,0.741624,0.474763,7.818979,...,2.375521,6.901386,0.989996,0.735689,2.686885,2.536054,1.257569,2.221733,0.663994,116.670332
5,4.275229,1.577051,5.414098,2.899092,27.018771,4.495894,3.353544,1.430885,1.401550,13.946013,...,5.262067,18.563854,2.993752,1.466298,6.309101,5.950422,2.450428,4.913294,1.520519,260.982624
6,4.724771,1.422949,5.585902,3.100908,27.981229,4.504106,3.646456,1.569115,1.598450,15.053987,...,5.737933,19.436146,3.006248,1.533702,6.690899,6.049578,2.549572,5.086706,1.479481,277.017376
7,6.320570,2.076705,8.884678,4.782738,34.966299,7.833322,5.648632,2.172109,1.368928,22.566944,...,8.816388,28.851403,5.398954,2.864612,9.204137,9.699821,4.703806,8.881968,2.798122,409.312193
8,2.374463,0.098746,0.514361,0.896046,3.690825,0.358520,0.709922,0.661291,1.372604,4.356281,...,1.800282,5.099585,0.063917,0.027711,2.557631,0.429850,0.189734,0.574416,0.000000,68.762937
9,0.073700,0.149187,0.286799,0.062136,7.742952,0.214691,0.218268,0.065396,0.109207,0.662505,...,0.124698,1.449022,0.117917,0.040874,0.670940,0.815721,0.025899,0.187934,0.020125,23.902578
10,0.054084,0.039343,0.462231,0.093276,5.671114,0.230125,0.256158,0.027280,0.051401,0.718894,...,0.061767,1.570266,0.170399,0.010122,0.168314,0.287751,0.010848,0.116195,0.000000,17.310124
11,0.132788,0.187025,0.334956,0.116034,2.250521,0.255720,0.149764,0.054489,0.084587,0.593949,...,0.156719,0.797815,0.133258,0.000000,0.355325,0.536903,0.060413,0.151924,0.000000,13.076962
12,0.194742,0.179185,2.596614,0.232375,16.737903,1.444713,0.860170,0.161614,0.209376,5.944493,...,0.270979,11.558421,0.546862,0.050294,0.719187,0.918359,0.054721,0.417486,0.226105,68.703255
13,6.192010,1.967470,6.970512,4.653912,25.007776,6.742819,5.139264,2.062117,1.249188,17.643158,...,8.626200,19.294321,5.061181,2.825430,8.736207,9.170266,4.662839,8.609143,2.616895,362.878886
14,0.287179,0.059972,0.345688,0.202037,2.441559,0.165194,0.177680,0.070003,0.065381,0.909061,...,0.379434,1.530470,0.080899,0.050624,0.342224,0.225371,0.179309,0.195365,0.047022,16.408965
15,0.875474,0.149052,0.789306,0.495142,3.523101,0.454124,0.375310,0.198103,0.141750,2.096437,...,0.873365,2.873686,0.323487,0.145540,0.808112,0.621963,0.437195,0.544351,0.179276,36.441642
16,2.831837,0.904384,2.771794,2.078677,12.134901,1.987938,1.915344,1.016896,0.566713,8.378941,...,3.565719,10.198273,1.425367,0.889055,3.292261,2.790012,1.982213,3.095957,0.888833,149.650756
17,2.149500,0.838200,3.035625,1.481691,14.073960,2.102623,1.407264,0.621568,0.461746,6.401311,...,2.577442,9.677246,1.695276,0.621164,2.845336,3.056318,1.054024,2.318810,0.832478,125.576021
18,0.753523,0.235037,0.975342,0.451593,4.594253,0.738925,0.532900,0.226111,0.077754,2.911027,...,0.810445,2.820107,0.617497,0.235869,0.987678,1.250931,0.356750,1.053169,0.318662,46.017496
19,1.354505,0.502253,1.976768,0.835215,11.723089,2.271506,1.485935,0.521534,0.781424,5.305679,...,1.802285,7.259508,1.242484,0.653924,2.766092,2.610399,0.613723,1.868755,0.470010,103.646542
20,0.747983,0.311102,1.105478,0.455645,6.509136,1.279690,1.105567,0.345784,0.905232,2.997544,...,0.991309,3.640711,0.614990,0.403825,1.958298,1.445006,0.376786,0.923593,0.263719,60.258578
21,7.837347,2.790976,9.865007,5.302821,49.035340,8.380682,6.447010,2.731894,2.792870,25.994502,...,9.747201,33.595844,5.595614,2.803835,11.849664,11.152666,4.383496,9.260284,2.773701,485.149393
22,2.102488,0.813354,3.082246,1.290860,18.232225,3.551195,2.591502,0.867318,1.686656,8.303223,...,2.793594,10.900219,1.857474,1.057748,4.724389,4.055406,0.990509,2.792348,0.733729,163.905121
23,8.753777,2.925457,10.726565,5.801514,53.809649,8.779772,6.751744,2.908801,2.835841,28.367407,...,10.704986,36.985836,5.898991,2.870801,12.546734,11.773444,4.852773,9.724585,2.923665,523.150422
24,1.272758,0.287750,1.184887,0.860420,5.507237,0.754200,0.601766,0.301433,0.413543,3.215213,...,1.384277,4.226121,0.491819,0.305910,1.200935,1.069123,0.777657,0.965829,0.291287,58.047015
25,7.481019,2.637708,9.541678,4.941094,48.302412,8.025572,6.149978,2.607369,2.422299,25.152194,...,9.320709,32.759716,5.407172,2.564890,11.345799,10.704321,4.075116,8.758756,2.632378,465.103407
26,0.121573,0.418184,0.132888,0.127359,0.168788,0.159160,0.208236,0.269355,0.493035,0.107453,...,0.114435,0.128939,0.208931,0.364678,0.153363,0.167625,0.154347,0.138633,0.429670,7.380112

In [17]:
data["Expected"] = expected
data["Actual"] = data[states].sum(axis=1)
data

,Label,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Expected,Actual
0,Citizens 18 years and over,9.000000,3.000000,11.000000,6.000000,55.000000,9.000000,7.000000,3.000000,3.000000,...,38.000000,6.000000,3.000000,13.000000,12.000000,5.000000,10.000000,3.000000,538.000000,1076.000000
1,18 to 29 years,1.863912,0.718520,2.418627,1.267668,12.832915,1.985161,1.393462,0.583144,0.828852,...,9.025246,1.631912,0.601992,2.749522,2.501283,0.933590,2.018466,0.601648,114.560540,229.184536
2,30 to 44 years,2.082082,0.815305,2.532192,1.408070,13.533895,2.389678,1.480566,0.636887,0.945451,...,9.929852,1.713929,0.619964,3.144732,3.016886,1.099672,2.287559,0.735818,127.556378,255.258969
3,45 to 64 years,3.054668,0.985200,3.411184,1.967572,17.548702,2.910914,2.536128,1.038345,0.750933,...,12.143516,1.664163,1.042355,4.418861,3.945777,1.709168,3.472243,0.998540,179.212749,358.258811
4,65 years and over,1.999338,0.480975,2.637997,1.356690,11.084488,1.714248,1.589844,0.741624,0.474763,...,6.901386,0.989996,0.735689,2.686885,2.536054,1.257569,2.221733,0.663994,116.670332,233.297684
5,Male,4.275229,1.577051,5.414098,2.899092,27.018771,4.495894,3.353544,1.430885,1.401550,...,18.563854,2.993752,1.466298,6.309101,5.950422,2.450428,4.913294,1.520519,260.982624,522.272420
6,Female,4.724771,1.422949,5.585902,3.100908,27.981229,4.504106,3.646456,1.569115,1.598450,...,19.436146,3.006248,1.533702,6.690899,6.049578,2.549572,5.086706,1.479481,277.017376,553.727580
7,White alone,6.320570,2.076705,8.884678,4.782738,34.966299,7.833322,5.648632,2.172109,1.368928,...,28.851403,5.398954,2.864612,9.204137,9.699821,4.703806,8.881968,2.798122,409.312193,820.557988
8,Black or African American alone,2.374463,0.098746,0.514361,0.896046,3.690825,0.358520,0.709922,0.661291,1.372604,...,5.099585,0.063917,0.027711,2.557631,0.429850,0.189734,0.574416,0.000000,68.762937,135.408673
9,Asian alone,0.073700,0.149187,0.286799,0.062136,7.742952,0.214691,0.218268,0.065396,0.109207,...,1.449022,0.117917,0.040874,0.670940,0.815721,0.025899,0.187934,0.020125,23.902578,47.501575
10,Some Other Race alone,0.054084,0.039343,0.462231,0.093276,5.671114,0.230125,0.256158,0.027280,0.051401,...,1.570266,0.170399,0.010122,0.168314,0.287751,0.010848,0.116195,0.000000,17.310124,33.928928
11,Two or More Races,0.132788,0.187025,0.334956,0.116034,2.250521,0.255720,0.149764,0.054489,0.084587,...,0.797815,0.133258,0.000000,0.355325,0.536903,0.060413,0.151924,0.000000,13.076962,26.267109
12,Hispanic or Latino,0.194742,0.179185,2.596614,0.232375,16.737903,1.444713,0.860170,0.161614,0.209376,...,11.558421,0.546862,0.050294,0.719187,0.918359,0.054721,0.417486,0.226105,68.703255,134.537987
13,"White alone, Not Hispanic or Latino",6.192010,1.967470,6.970512,4.653912,25.007776,6.742819,5.139264,2.062117,1.249188,...,19.294321,5.061181,2.825430,8.736207,9.170266,4.662839,8.609143,2.616895,362.878886,729.832526
14,Less than 9th grade,0.287179,0.059972,0.345688,0.202037,2.441559,0.165194,0.177680,0.070003,0.065381,...,1.530470,0.080899,0.050624,0.342224,0.225371,0.179309,0.195365,0.047022,16.408965,32.553153
15,"9th to 12th grade, no diploma",0.875474,0.149052,0.789306,0.495142,3.523101,0.454124,0.375310,0.198103,0.141750,...,2.873686,0.323487,0.145540,0.808112,0.621963,0.437195,0.544351,0.179276,36.441642,72.545916
16,High school graduate (includes equival...,2.831837,0.904384,2.771794,2.078677,12.134901,1.987938,1.915344,1.016896,0.566713,...,10.198273,1.425367,0.889055,3.292261,2.790012,1.982213,3.095957,0.888833,149.650756,299.762230
17,"Some college, no degree",2.149500,0.838200,3.035625,1.481691,14.073960,2.102623,1.407264,0.621568,0.461746,...,9.677246,1.695276,0.621164,2.845336,3.056318,1.054024,2.318810,0.832478,125.576021,251.391992
18,Associate's degree,0.753523,0.235037,0.975342,0.451593,4.594253,0.738925,0.532900,0.226111,0.077754,...,2.820107,0.617497,0.235869,0.987678,1.250931,0.356750,1.053169,0.318662,46.017496,92.192753
19,Bachelor's degree,1.354505,0.502253,1.976768,0.835215,11.723089,2.271506,1.485935,0.521534,0.781424,...,7.259508,1.242484,0.653924,2.766092,2.610399,0.613723,1.868755,0.470010,103.646542,207.073429
20,Graduate or professional degree,0.747983,0.311102,1.105478,0.455645,6.509136,1.279690,1.105567,0.345784,0.905232,...,3.640711,0.614990,0.403825,1.958298,1.445006,0.376786,0.923593,0.263719,60.258578,120.480526
21,High school degree or higher,7.837347,2.790976,9.865007,5.302821,49.035340,8.380682,6.447010,2.731894,2.792870,...,33.595844,5.595614,2.803835,11.849664,11.152666,4.383496,9.260284,2.773701,485.149393,970.900931
22,Bachelor's degree or higher,2.102488,0.813354,3.082246,1.290860,18.232225,3.551195,2.591502,0.867318,1.686656,...,10.900219,1.857474,1.057748,4.724389,4.055406,0.990509,2.792348,0.733729,163.905121,327.553956
23,"Total Citizens, 18 years and older, fo...",8.753777,2.925457,10.726565,5.801514,53.809649,8.779772,6.751744,2.908801,2.835841,...,36.985836,5.898991,2.870801,12.546734,11.773444,4.852773,9.724585,2.923665,523.150422,1046.144496
24,Income in the past 12 months below pov...,1.272758,0.287750,1.184887,0.860420,5.507237,0.754200,0.601766,0.301433,0.413543,...,4.226121,0.491819,0.305910,1.200935,1.069123,0.777657,0.965829,0.291287,58.047015,116.119569
25,Income in the past 12 months at or abo...,7.481019,2.637708,9.541678,4.941094,48.302412,8.025572,6.149978,2.607369,2.422299,...,32.759716,5.407172,2.564890,11.345799,10.704321,4.075116,8.758756,2.632378,465.103407,930.024927
26,Median Household Income for Households...,0.121573,0.418184,0.132888,0.127359,0.168788,0.159160,0.208236,0.269355,0.493035,...,0.128939,0.208931,0.364678,0.153363,0.167625,0.154347,0.138633,0.429670,7.380112,17.062975

In [21]:
eva = pd.DataFrame({
    "Label": data.Label,
    "Delta": data.Actual - data.Expected
})
eva

                                                Label     Delta
0                          Citizens 18 years and over  0.000000
1                                      18 to 29 years  0.056454
2                                      30 to 44 years  0.104765
3                                      45 to 64 years -0.144754
4                                   65 years and over -0.016465
5                                                Male  0.268410
6                                              Female -0.268410
7                                         White alone  1.845224
8                     Black or African American alone -2.096316
9                                         Asian alone -0.272461
10                              Some Other Race alone -0.637557
11                                  Two or More Races  0.101299
12                                 Hispanic or Latino -3.072580
13                White alone, Not Hispanic or Latino  4.241291
14                                Less than 9th grade -0.301714
15                      9th to 12th grade, no diploma -0.334252
16          High school graduate (includes equival...  0.537920
17                            Some college, no degree  0.176023
18                                 Associate's degree  0.153373
19                                  Bachelor's degree -0.210448
20                    Graduate or professional degree -0.020902
21                       High school degree or higher  0.635966
22                        Bachelor's degree or higher -0.231350
23          Total Citizens, 18 years and older, fo... -0.162589
24          Income in the past 12 months below pov...  0.004089
25          Income in the past 12 months at or abo... -0.166677
26          Median Household Income for Households...  2.425081